### ISSUE TITLE
GroupValueResponse is ignored

### ISSUE THREAD

**Issue by skrutzler** [ioBroker/ioBroker.knx#162] opened 2021-03-25 13:18 UTC
Once the iobroker knx adapter sends a GroupValueRead (Object with R&W flag) the knx bus shows that there is also a GroupValueResponse, but that one is ignored. The Iobroker object stays at 0°C.
The iobroker object is only updated once the knx device is sending the KNX Object on its own.
```
# | Zeit | Dienst | Flags | Prio | Quelladresse | Quellname | Zieladresse | Zielname | Rout | Typ | DPT | Info
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2709 | 25.03.2021 14:14:33,345 | vom Bus |   | Niedrig | 1.0.199 | IO-Broker | 5/0/15 | EG - Wohnzimmer - Temperatur | 6 | GroupValueRead |   |  
2710 | 25.03.2021 14:14:33,448 | vom Bus |   | Niedrig | 1.0.30 | Wohnzimmer Präsenzmelder Multisensor | 5/0/15 | EG - Wohnzimmer - Temperatur | 6 | GroupValueResponse | 9.001 Temperatur (°C) | 0C 79 \| 22,9 °C
```

Version 1.0.44

**Comment by Videonisse** [comment] 2021-03-27 15:11
I have the same problem. Have tested with all the versions v1.0.41 to 1.0.45 without success. 

I actually thought this was working earlier but not sure anymore. I tried using the older knxproj-file from ETS 5.7.4 together with the above versions and used a clean installation of the Instance every time. Lastly, I also removed the KNX Adapter and reinstalled the latest version and created a new instance with import from ETS 5.7.5. Problem persists.

Also tested to change the State DB from File to Redis, but didn't help.

The problem seems to be with all DPs, but the one if mostly tested with is a Dimmer Level Status % for a Light. DPT5.001.

See below several parts of the log-file. The first log level was set to More but for the lasts I changed to Most. They are all from v.1.0.45.

**DP Object - GA 4/7/21**
`
{
  "_id": "knx.1.Belysning.Dimmer.Kök_Ljusskena_matbord_LGx1_Status_Dimvärde_8bit",
  "type": "state",
  "common": {
    "name": "Kök Ljusskena matbord LGx1 Status Dimvärde 8bit",
    "type": "number",
    "role": "value",
    "read": true,
    "write": true,
    "unit": "%",
    "max": 100,
    "min": 0
  },
  "native": {
    "dpt": "DPT5.001",
    "address": "4/7/21",
    "addressRefId": "P-095B-0_GA-13",
    "statusGARefId": "",
    "actGARefId": "P-095B-0_GA-10",
    "update": false,
    "objRef": "O-10_R-1627",
    "devName": "M-0048_A-493A-1C-D4B1",
    "devInst": "P-095B-0_DI-16",
    "objectSize": ""
  },
  "from": "system.adapter.knx.1",
  "user": "system.user.admin",
  "ts": 1616846273617,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
`


**Log-file - after setting-up a new Instance of KNX Adapter v1.0.45 and importing knxprojekt-file from ETS 5.7.5:  DP State = null, error in log "Received TUNNEL_REQUEST for unexpected address"**

`2021-03-27 13:46:11.236 - info: knx.0 (2151) ( 3.1 ) Received TUNNEL_REQUEST (READ - ACK) : 06 10 04 20 00 15 04 22 40 00 29 00 bc e0 11 fa 27 15 01 00 00 34
2021-03-27 13:46:11.237 - info: knx.0 (2151) main.js: Received Value from GroupValue Read
2021-03-27 13:46:11.237 - info: knx.0 (2151) main.js: onGroupValue_Read from 4/7/21
2021-03-27 13:46:11.237 - info: knx.0 (2151) READ : mappedName : Kök Ljusskena matbord LGx1 Status Dimvärde 8bit dest : 4/7/21 val: 0 (DPT5.001) Kök_Ljusskena_matbord_LGx1_Status_Dimvärde_8bit
2021-03-27 13:46:11.237 - info: knx.0 (2151) READ single-array value : 0 auf knx.0.Belysning.Dimmer.Kök_Ljusskena_matbord_LGx1_Status_Dimvärde_8bit
2021-03-27 13:46:11.238 - info: knx.0 (2151) =====> STATE_TUNNELING_ACK
2021-03-27 13:46:11.238 - info: knx.0 (2151) ( 4 ) Sending Tunnel_Request ACK : 06 10 04 21 00 0a 04 22 40 00 ChID : 34 SeqCntIN : 64 SeqCntOUT : 35 queue length : 0
2021-03-27 13:46:11.238 - info: knx.0 (2151) ( 4.b ) return to STATE_READY, processing : false
2021-03-27 13:46:11.288 - info: knx.0 (2151) ( 3.3 ) Received TUNNEL_REQUEST (RESPONSE - send ACK) : 06 10 04 20 00 16 04 22 41 00 29 00 bc e0 11 01 27 15 02 00 40 66 34
2021-03-27 13:46:11.289 - info: knx.0 (2151) main.js: onGroupValue_Response from 4/7/21
2021-03-27 13:46:11.289 - info: knx.0 (2151) RESPONSE : mappedName : Kök Ljusskena matbord LGx1 Status Dimvärde 8bit dest : 4/7/21 val: 40 (DPT5.001) Kök_Ljusskena_matbord_LGx1_Status_Dimvärde_8bit
2021-03-27 13:46:11.289 - info: knx.0 (2151) RESPONSE single-array value : 40 auf knx.0.Belysning.Dimmer.Kök_Ljusskena_matbord_LGx1_Status_Dimvärde_8bit
2021-03-27 13:46:11.290 - info: knx.0 (2151) ( 3.4 ) Received TUNNEL_REQUEST for unexpected address
2021-03-27 13:46:11.290 - info: knx.0 (2151) =====> STATE_TUNNELING_ACK
2021-03-27 13:46:11.291 - info: knx.0 (2151) ( 4 ) Sending Tunnel_Request ACK : 06 10 04 21 00 0a 04 22 41 00 ChID : 34 SeqCntIN : 65 SeqCntOUT : 35 queue length : 0
2021-03-27 13:46:11.291 - info: knx.0 (2151) ( 4.b ) return to STATE_READY, processing : false`



**Log-file - after stopping KNX Adapter and changing the % value using Busmonitor from 35% to 50%. Then starting KNX Adapter again. The object state/value is NOT updated in KNX Adapter, but the adpter receives the new value!**

`2021-03-27 14:17:12.486 - info: knx.0 (2203) Has todo still 20 tasks, just processing : false
2021-03-27 14:17:12.653 - info: knx.0 (2203) ( 1 ) Sending : GroupValueRead : 06 10 04 20 00 15 04 03 0f 00 11 00 bc e0 11 f8 27 15 01 00 00 sent to 192.168.10.20:3671 ChID: 3 SeqCntIN : 20 SeqCntOUT : 15 GA : 4/7/21 conCheck.conected : true
2021-03-27 14:17:12.654 - info: knx.0 (2203) easy-knx: task.data : 06 10 04 20 00 15 04 03 0f 00 11 00 bc e0 11 f8 27 15 01 00 00 byteLen : 21
2021-03-27 14:17:12.657 - info: knx.0 (2203) ( 2 ) Received TUNNEL_ACK : 06 10 04 21 00 0a 04 03 0f 00 from 192.168.10.20:3671 SeqCntIN : 20 SeqCntOUT : 16 GA : 0/0/0
2021-03-27 14:17:12.657 - info: knx.0 (2203) ==> successful acknowledged previous package... processing next of 19
2021-03-27 14:17:12.658 - info: knx.0 (2203) ==> easy-knx.js: signal runtime : 0s 4.516945ms
2021-03-27 14:17:12.658 - info: knx.0 (2203) Has todo still 19 tasks, just processing : false
2021-03-27 14:17:12.658 - info: knx.0 (2203) ( 3.1 ) Received TUNNEL_REQUEST (READ - ACK) : 06 10 04 20 00 15 04 03 15 00 29 00 bc e0 11 f8 27 15 01 00 00 3
2021-03-27 14:17:12.659 - info: knx.0 (2203) main.js: Received Value from GroupValue Read
2021-03-27 14:17:12.659 - info: knx.0 (2203) main.js: onGroupValue_Read from 4/7/21
2021-03-27 14:17:12.659 - info: knx.0 (2203) READ : mappedName : Kök Ljusskena matbord LGx1 Status Dimvärde 8bit dest : 4/7/21 val: 0 (DPT5.001) Kök_Ljusskena_matbord_LGx1_Status_Dimvärde_8bit
2021-03-27 14:17:12.659 - info: knx.0 (2203) READ single-array value : 0 auf knx.0.Belysning.Dimmer.Kök_Ljusskena_matbord_LGx1_Status_Dimvärde_8bit
2021-03-27 14:17:12.659 - info: knx.0 (2203) =====> STATE_TUNNELING_ACK
2021-03-27 14:17:12.660 - info: knx.0 (2203) ( 4 ) Sending Tunnel_Request ACK : 06 10 04 21 00 0a 04 03 15 00 ChID : 3 SeqCntIN : 21 SeqCntOUT : 16 queue length : 19
2021-03-27 14:17:12.660 - info: knx.0 (2203) ( 4.b ) return to STATE_READY, processing : false
2021-03-27 14:17:12.661 - info: knx.0 (2203) Has todo still 19 tasks, just processing : false2021-03-27 12:58:04.923 - info: knx.1 (1281) ( 4.b ) return to STATE_READY, processing : false`



**Log-file - when it works. This one, it receives a GroupValueWrite from Bus and updates 4/7/21. Also works when a Write is done to 4/7/18 from KNX Adapter.**

`2021-03-27 14:10:18.842 - info: knx.0 (2151) ( 3.2 ) Received TUNNEL_REQUEST (WRITE - send ACK ) : 06 10 04 20 00 16 04 01 0d 00 29 00 bc e0 11 fb 27 12 02 00 80 59 ChID: 1
2021-03-27 14:10:18.842 - info: knx.0 (2151) WRITE : mappedName : Kök Ljusskena matbord LGx1 Dimvärde 8bit dest : 4/7/18 val: 35 (DPT5.001) Kök_Ljusskena_matbord_LGx1_Dimvärde_8bit
2021-03-27 14:10:18.843 - info: knx.0 (2151) =====> STATE_TUNNELING_ACK
2021-03-27 14:10:18.843 - info: knx.0 (2151) ( 4 ) Sending Tunnel_Request ACK : 06 10 04 21 00 0a 04 01 0d 00 ChID : 1 SeqCntIN : 13 SeqCntOUT : 3 queue length : 0
2021-03-27 14:10:18.843 - info: knx.0 (2151) ( 4.b ) return to STATE_READY, processing : false
2021-03-27 14:10:19.148 - info: knx.0 (2151) ( 3.2 ) Received TUNNEL_REQUEST (WRITE - send ACK ) : 06 10 04 20 00 16 04 01 0e 00 29 00 bc e0 11 01 27 15 02 00 80 59 ChID: 1
2021-03-27 14:10:19.149 - info: knx.0 (2151) WRITE : mappedName : Kök Ljusskena matbord LGx1 Status Dimvärde 8bit dest : 4/7/21 val: 35 (DPT5.001) Kök_Ljusskena_matbord_LGx1_Status_Dimvärde_8bit
2021-03-27 14:10:19.149 - info: knx.0 (2151) =====> STATE_TUNNELING_ACK
2021-03-27 14:10:19.150 - info: knx.0 (2151) ( 4 ) Sending Tunnel_Request ACK : 06 10 04 21 00 0a 04 01 0e 00 ChID : 1 SeqCntIN : 14 SeqCntOUT : 3 queue length : 0
2021-03-27 14:10:19.150 - info: knx.0 (2151) ( 4.b ) return to STATE_READY, processing : false`


**Log-file (log level changed from More to Most) - after removing KNX Adapter installation and reinstalling Adapter and Instance: Response values are still NOT written to State or Object.**

`2021-03-27 15:28:55.913 - info: knx.0 (1324) Has todo still 19 tasks, just processing : false
2021-03-27 15:28:55.913 - info: knx.0 (1324) ( 3.1 ) Received TUNNEL_REQUEST (READ - ACK) : 06 10 04 20 00 15 04 14 15 00 29 00 bc e0 11 f8 27 15 01 00 00 20
2021-03-27 15:28:55.913 - info: knx.0 (1324) main.js: Received Value from GroupValue Read
2021-03-27 15:28:55.913 - info: knx.0 (1324) main.js: onGroupValue_Read from 4/7/21
2021-03-27 15:28:55.914 - info: knx.0 (1324) READ : mappedName : Kök Ljusskena matbord LGx1 Status Dimvärde 8bit dest : 4/7/21 val: 0 (DPT5.001) Kök_Ljusskena_matbord_LGx1_Status_Dimvärde_8bit
2021-03-27 15:28:55.914 - info: knx.0 (1324) READ single-array value : 0 auf knx.0.Belysning.Dimmer.Kök_Ljusskena_matbord_LGx1_Status_Dimvärde_8bit
2021-03-27 15:28:55.914 - info: knx.0 (1324) Change state from STATE_READY(7) to STATE_TUNNELLING_REQUEST(13)
2021-03-27 15:28:55.914 - info: knx.0 (1324) Change state from STATE_TUNNELLING_REQUEST(13) to STATE_TUNNELLING_ACK(14)
2021-03-27 15:28:55.914 - info: knx.0 (1324) =====> STATE_TUNNELING_ACK
2021-03-27 15:28:55.915 - info: knx.0 (1324) ( 4 ) Sending Tunnel_Request ACK : 06 10 04 21 00 0a 04 14 15 00 ChID : 20 SeqCntIN : 21 SeqCntOUT : 16 queue length : 19
2021-03-27 15:28:55.915 - info: knx.0 (1324) ( 4.b ) return to STATE_READY, processing : false
2021-03-27 15:28:55.915 - info: knx.0 (1324) Change state from STATE_TUNNELLING_ACK(14) to STATE_READY(7)
2021-03-27 15:28:55.915 - info: knx.0 (1324) Has todo still 19 tasks, just processing : false
2021-03-27 15:28:55.963 - info: knx.0 (1324) ( 3.3 ) Received TUNNEL_REQUEST (RESPONSE - send ACK) : 06 10 04 20 00 16 04 14 16 00 29 00 bc e0 11 01 27 15 02 00 40 80 20
2021-03-27 15:28:55.964 - info: knx.0 (1324) main.js: onGroupValue_Response from 4/7/21
2021-03-27 15:28:55.964 - info: knx.0 (1324) RESPONSE : mappedName : Kök Ljusskena matbord LGx1 Status Dimvärde 8bit dest : 4/7/21 val: 50 (DPT5.001) Kök_Ljusskena_matbord_LGx1_Status_Dimvärde_8bit
2021-03-27 15:28:55.964 - info: knx.0 (1324) RESPONSE single-array value : 50 auf knx.0.Belysning.Dimmer.Kök_Ljusskena_matbord_LGx1_Status_Dimvärde_8bit
2021-03-27 15:28:55.965 - info: knx.0 (1324) Change state from STATE_READY(7) to STATE_TUNNELLING_REQUEST(13)
2021-03-27 15:28:55.965 - info: knx.0 (1324) Change state from STATE_TUNNELLING_REQUEST(13) to STATE_TUNNELLING_ACK(14)
2021-03-27 15:28:55.965 - info: knx.0 (1324) =====> STATE_TUNNELING_ACK
2021-03-27 15:28:55.965 - info: knx.0 (1324) ( 4 ) Sending Tunnel_Request ACK : 06 10 04 21 00 0a 04 14 16 00 ChID : 20 SeqCntIN : 22 SeqCntOUT : 16 queue length : 19
2021-03-27 15:28:55.966 - info: knx.0 (1324) ( 4.b ) return to STATE_READY, processing : false
2021-03-27 15:28:55.966 - info: knx.0 (1324) Change state from STATE_TUNNELLING_ACK(14) to STATE_READY(7)
2021-03-27 15:28:55.966 - info: knx.0 (1324) Has todo still 19 tasks, just processing : false`


**Log-file (Most) - triggering a Read from Status-object in KNX Adapter, sending a 0% to 4/7/21. The respons, value 50%, is recieved but DP object is not updated!**

`2021-03-27 15:37:07.193 - info: knx.0 (1324) main.js : tGA.write on Statechange : 4/7/21 P-095B-0_GA-13 typeof val: number 0 DPT5.001
2021-03-27 15:37:07.194 - info: knx.0 (1324) add to Buffer cnt: 37 : 06 10 04 20 00 15 04 14 25 00 11 00 bc e0 11 f8 27 15 01 00 00 queue.length : 0 GA : 4/7/21
2021-03-27 15:37:07.194 - info: knx.0 (1324) Change state from STATE_READY(7) to STATE_TUNNELLING_SENDING_DATA(8)
2021-03-27 15:37:07.195 - info: knx.0 (1324) ( 1 ) Sending : GroupValueRead : 06 10 04 20 00 15 04 14 25 00 11 00 bc e0 11 f8 27 15 01 00 00 sent to 192.168.10.20:3671 ChID: 20 SeqCntIN : 62 SeqCntOUT : 37 GA : 4/7/21 conCheck.conected : true
2021-03-27 15:37:07.195 - info: knx.0 (1324) easy-knx: task.data : 06 10 04 20 00 15 04 14 25 00 11 00 bc e0 11 f8 27 15 01 00 00 byteLen : 21
2021-03-27 15:37:07.195 - info: knx.0 (1324) Change state from STATE_TUNNELLING_SENDING_DATA(8) to STATE_TUNNELLING_WAIT_SENT_ACK(9)
2021-03-27 15:37:07.197 - info: knx.0 (1324) ( 2 ) Received TUNNEL_ACK : 06 10 04 21 00 0a 04 14 25 00 from 192.168.10.20:3671 SeqCntIN : 62 SeqCntOUT : 38 GA : 0/0/0
2021-03-27 15:37:07.197 - info: knx.0 (1324) Change state from STATE_TUNNELLING_WAIT_SENT_ACK(9) to STATE_TUNNELLING_SENT_DATA_ACK_RECV(11)
2021-03-27 15:37:07.197 - info: knx.0 (1324) STATE_TUNNELLING_WAIT_SENT_ACK: received ACK for previous self sent package
2021-03-27 15:37:07.197 - info: knx.0 (1324) ==> successful acknowledged previous package... processing next of 0
2021-03-27 15:37:07.197 - info: knx.0 (1324) Change state from STATE_TUNNELLING_SENT_DATA_ACK_RECV(11) to STATE_READY(7)
2021-03-27 15:37:07.198 - info: knx.0 (1324) ==> easy-knx.js: signal runtime : 0s 3.273299ms
2021-03-27 15:37:07.198 - info: knx.0 (1324) ( 3.1 ) Received TUNNEL_REQUEST (READ - ACK) : 06 10 04 20 00 15 04 14 3f 00 29 00 bc e0 11 f8 27 15 01 00 00 20
2021-03-27 15:37:07.198 - info: knx.0 (1324) main.js: ignoring Received Value from GroupValue Read, because it was my own Read request.
2021-03-27 15:37:07.198 - info: knx.0 (1324) Change state from STATE_READY(7) to STATE_TUNNELLING_REQUEST(13)
2021-03-27 15:37:07.199 - info: knx.0 (1324) Change state from STATE_TUNNELLING_REQUEST(13) to STATE_TUNNELLING_ACK(14)
2021-03-27 15:37:07.199 - info: knx.0 (1324) =====> STATE_TUNNELING_ACK
2021-03-27 15:37:07.199 - info: knx.0 (1324) ( 4 ) Sending Tunnel_Request ACK : 06 10 04 21 00 0a 04 14 3f 00 ChID : 20 SeqCntIN : 63 SeqCntOUT : 38 queue length : 0
2021-03-27 15:37:07.200 - info: knx.0 (1324) ( 4.b ) return to STATE_READY, processing : false
2021-03-27 15:37:07.200 - info: knx.0 (1324) Change state from STATE_TUNNELLING_ACK(14) to STATE_READY(7)
2021-03-27 15:37:07.251 - info: knx.0 (1324) ( 3.3 ) Received TUNNEL_REQUEST (RESPONSE - send ACK) : 06 10 04 20 00 16 04 14 40 00 29 00 bc e0 11 01 27 15 02 00 40 80 20
2021-03-27 15:37:07.251 - info: knx.0 (1324) main.js: onGroupValue_Response from 4/7/21
2021-03-27 15:37:07.252 - info: knx.0 (1324) RESPONSE : mappedName : Kök Ljusskena matbord LGx1 Status Dimvärde 8bit dest : 4/7/21 val: 50 (DPT5.001) Kök_Ljusskena_matbord_LGx1_Status_Dimvärde_8bit
2021-03-27 15:37:07.252 - info: knx.0 (1324) RESPONSE single-array value : 50 auf knx.0.Belysning.Dimmer.Kök_Ljusskena_matbord_LGx1_Status_Dimvärde_8bit
2021-03-27 15:37:07.252 - info: knx.0 (1324) Change state from STATE_READY(7) to STATE_TUNNELLING_REQUEST(13)
2021-03-27 15:37:07.253 - info: knx.0 (1324) Change state from STATE_TUNNELLING_REQUEST(13) to STATE_TUNNELLING_ACK(14)
2021-03-27 15:37:07.253 - info: knx.0 (1324) =====> STATE_TUNNELING_ACK
2021-03-27 15:37:07.253 - info: knx.0 (1324) ( 4 ) Sending Tunnel_Request ACK : 06 10 04 21 00 0a 04 14 40 00 ChID : 20 SeqCntIN : 64 SeqCntOUT : 38 queue length : 0
2021-03-27 15:37:07.253 - info: knx.0 (1324) ( 4.b ) return to STATE_READY, processing : false
2021-03-27 15:37:07.254 - info: knx.0 (1324) Change state from STATE_TUNNELLING_ACK(14) to STATE_READY(7)`

**Comment by Videonisse** [comment] 2021-04-04 22:08
@chefkoch009 Any chance you could confirm if this actually is a bug in the Adapter, or if it works as it should on other installations?

As I also wrote on the [Forum](https://forum.iobroker.net/topic/26167/test-adapter-knx-v1-0-x/442?_=1616858621504), it's very easy to reproduce:

* Benutzte ein Dimmer Licht. Schalte es mal ein und kontrolliere die Status wert (%) in ioBroker (DPT5.001)
* KNX Adapter Instanz anhalten
* Ändere Dimmer wert (Busmonitor oder an Schalter)
* Starte KNX Adapter
* Beobachte ob Dimmer Status wert in ioBroker upgedatet wird oder nicht, ohne die Lampe zu schalten/dimmern.

**Comment by skrutzler** [comment] 2021-04-12 05:32
is there any progress on this topic or can I somewhere help?
This is a rather serious issue and makes the iobroker/adapter not usable for me.

**Comment by RESDE** [comment] 2021-04-16 11:04
@Videonisse the communication between the KNX Gateway and the KNX adapter is heavily depending on your ETS setup ( gateway. In many other users all state updates driven from IOBroker are working coorrectly. 
Before keeping flodding this topic with long log protocolls which are hard to read anyway I can offer you to import your ETS project file and test out what else can impact the propper communication from/into the ETS world. Please send me an PN to my github user.
@skrutzler: the KNX adapter only reacts based on the propper import of the GA addresses. Many issues are here available where it is proven that wrong flags in the GA setup in ETS leads not to a propper KNX adapter data exchange. Have you read all these issues and are you clear that the GA flags in your ETS project are set accurately. 
If you can confirm this would you mind to post then the relevant GA adresses with a screenshot of the ETS (and with the linked devices) and then as well the object definitions out of the knx adapter (especially the read/write tru/efalse options)

**Comment by Videonisse** [comment] 2021-04-16 13:09
@RESDE Sorry but I don't know how to send a PM to a GitHub user, is it possible?

I created a test project with just one light and has been testing this with a separate instance of the KNX Adapter. My KNX interface is a Weinzierl KNX IP Interface 730. Using this I have exactly the same problem as when I'm using my production setup.

Are you 100% sure that there is no problem with other installations where it seems to work? Have you tried to reproduce the issue as I tried to explain above?

First I was sure it was working for me as well, as time stamp and everything indicates this, but it's not. I have asked in the forum if someone could do the test and confirm if it work for not for them, but no one as answered. Until it's confirmed, I believe it actually is a bug.

Here is my knxproj file:
[ioBroker test GroupValueRespons.zip](https://github.com/ioBroker/ioBroker.knx/files/6325222/ioBroker.test.GroupValueRespons.zip)

(How can I paste log files without that Githib removes the linebreaks?)

**Comment by Videonisse** [comment] 2021-04-16 13:33
Below is again some log information as screen dumps instead of text.

(The value was 40%, then is Adapter turned off and the value changed in KNX to 37%. When the Adapter is turned on, it sends a GroupValueRead and also receives the new value of 37%. Timestamp for Object is updated BUT THE NEW VALUE IS NOT WRITTEN TO OBJECT:

**ioBroker Log**
![image](https://user-images.githubusercontent.com/13684218/115030751-b9ee1300-9ec7-11eb-8b1b-fe0e491eec8c.png)

**ioBroker Objects**
![image](https://user-images.githubusercontent.com/13684218/115030954-f02b9280-9ec7-11eb-9dd8-2bca2d7b37cc.png)

**ETS5 Busmonitor**
![image](https://user-images.githubusercontent.com/13684218/115031446-747e1580-9ec8-11eb-8a2a-691a7f5dffda.png)

**Comment by RESDE** [comment] 2021-04-18 08:04
@Videonisse for a PN just check out my User RES_DE in the IOBroker Forum there is the opportunity that we xchange Themen

**Comment by Videonisse** [comment] 2021-04-29 08:01
Clarification regarding the problem: There is no problem with the "response" values for boolean values or numbers that is = 0 (zero). I have tested numbers with 1 byte DPT 5.001 (%) and 2 bytes DPT 7.012 (mA).

The problem is with values greater than 0 (zero). They are received (visible in adapter log) but NOT written to the state database and not updated in the object.

Anyone else with the same problem?

**Comment by Videonisse** [comment] 2021-05-11 08:40
@chefkoch009 are there any chance you could give some feedback regarding your thoughts about this issue?

It's really quick and easy to reproduce and if the above screen dumps wasn't clear enough, below shows with 100% certainty that that response value is received by the KNX Adapter but NOT written to the state database. If this isn't a serious bug in the KNX Adapter, what is the cause of the problem? 

The easiest way to reproduce the Issue:
1. Switch a dimmer light off. Notice the dim value object (should be 0%)
2. Turn off KNX Adapter instance
3. Switch the dimmer light on
4. Turn on KNX Adapter instance
5. Notice the dim value object (should anything else than 0%)

In the below screen dumps, in step 5, the dim value remains 0% but log shows clearly that a value of 50% was received. Timestamp confirmed that the object was updated, but not with the new value.

**Step1:**
![image](https://user-images.githubusercontent.com/13684218/117783464-da995680-b242-11eb-862b-12b6112b0c92.png)


**Step 5:**
![image](https://user-images.githubusercontent.com/13684218/117783627-04527d80-b243-11eb-9fa1-fab4b0e1445f.png)

![image](https://user-images.githubusercontent.com/13684218/117783856-382da300-b243-11eb-8bde-1170d61bcf66.png)


**Additional:** if the light is toggled off/on when KNX Adapter is active, the problem will not be identified as the new value is received as GroupValueWrite.
![image](https://user-images.githubusercontent.com/13684218/117785600-087f9a80-b245-11eb-8bc6-ddd0cd166883.png)

**Comment by skrutzler** [comment] 2021-06-17 05:19
so the issue is reproducable. is there any progress?

**Comment by Videonisse** [comment] 2021-12-04 11:47
@chefkoch009 This Issue remains with v2.0.2. Any idea why the value is not updated?

**Comment by FMode** [comment] 2022-01-08 23:23
I can reproduce this bug too with 2.0.8.

**Comment by Drkongo** [comment] 2022-02-17 20:12
Any news on this topic.
I have the same problem with v. 2.0.5. 
My temperature objects stay with value null.

**Comment by chefkoch009** [comment] 2022-02-25 20:27
i fixed in V2.0.12 some things related to this issue. could you check it please?

**Comment by Videonisse** [comment] 2022-02-26 11:06
Nice, thanks! I have only done one quick test (the one explained above) and now it works! I appreciate your effort!

**Comment by chefkoch009** [comment] 2022-02-26 19:45
so, this issue can be closed?

**Comment by Videonisse** [comment] 2022-02-26 20:43
From my perspective yes. Maybe also issue #122 can be closed?

**Comment by chefkoch009** [comment] 2022-02-26 22:26
Great. So I close this issue... thanks for response.

**Closed by chefkoch009** 2022-02-26 22:26 UTC
