### ISSUE TITLE
Verbindungsabbrüche

### ISSUE THREAD

**Issue by Sirfauntleroy** [ioBroker/ioBroker.knx#185] opened 2021-07-10 12:04 UTC
Hallo Zusammen.

Ich habe leider regelmäßig im Abstand von einigen Minuten Verbindungsabrisse der Instanz zur Schnittstelle.
(MDT SCN-IP000.03 IP Interface)

diese treten nach einigen Minuten, aber ohne erkennbares Muster auf.

Betrieben wird das ganz in einem Unifi-Netzwerk mit USG und 2 managed switches sowie dem Cloudkey.

`
<html><body>

knx.0 | 30918 | 2021-07-10 13:59:41.925 | info | Connected  - local UDP Server listening on 192.168.10.11:45800
-- | -- | -- | -- | --
knx.0 | 30918 | 2021-07-10 13:59:39.924 | info | STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0).
knx.0 | 30918 | 2021-07-10 13:59:37.922 | info | Connected  - local UDP Server listening on 192.168.10.11:53905
knx.0 | 30918 | 2021-07-10 13:59:35.920 | info | STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0).
knx.0 | 30918 | 2021-07-10 13:59:33.917 | info | Connected  - local UDP Server listening on 192.168.10.11:38729
knx.0 | 30918 | 2021-07-10 13:59:31.915 | info | STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0).
knx.0 | 30918 | 2021-07-10 13:59:29.913 | info | Connected  - local UDP Server listening on 192.168.10.11:34264
knx.0 | 30918 | 2021-07-10 13:59:27.913 | info | STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0).
knx.0 | 30918 | 2021-07-10 13:59:25.909 | info | Connected  - local UDP Server listening on 192.168.10.11:38910
knx.0 | 30918 | 2021-07-10 13:59:23.907 | info | STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0).
knx.0 | 30918 | 2021-07-10 13:59:21.904 | info | Connected  - local UDP Server listening on 192.168.10.11:46129
knx.0 | 30918 | 2021-07-10 13:59:19.904 | info | STATE_NOT_CONNECTED : Stop connection :  STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 30918 | 2021-07-10 13:59:19.903 | info | STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_READY(7) to STATE_NOT_CONNECTED(0).
knx.0 | 30918 | 2021-07-10 13:59:04.907 | info | Connected  - local UDP Server listening on 192.168.10.11:43468
knx.0 | 30918 | 2021-07-10 13:59:02.908 | info | STATE_NOT_CONNECTED : Stop connection :  STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 30918 | 2021-07-10 13:59:02.905 | info | STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_READY(7) to STATE_NOT_CONNECTED(0).
knx.0 | 30918 | 2021-07-10 13:57:55.860 | info | Connected  - local UDP Server listening on 192.168.10.11:37378
knx.0 | 30918 | 2021-07-10 13:57:53.858 | info | STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0).
knx.0 | 30918 | 2021-07-10 13:57:51.855 | info | Connected  - local UDP Server listening on 192.168.10.11:34860
knx.0 | 30918 | 2021-07-10 13:57:49.853 | info | STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0).
knx.0 | 30918 | 2021-07-10 13:57:47.852 | info | Connected  - local UDP Server listening on 192.168.10.11:54445
knx.0 | 30918 | 2021-07-10 13:57:45.849 | info | STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0).
knx.0 | 30918 | 2021-07-10 13:57:43.845 | info | Connected  - local UDP Server listening on 192.168.10.11:55079
knx.0 | 30918 | 2021-07-10 13:57:41.844 | info | STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0).
knx.0 | 30918 | 2021-07-10 13:57:39.840 | info | Connected  - local UDP Server listening on 192.168.10.11:44458
knx.0 | 30918 | 2021-07-10 13:57:37.838 | info | STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0).
knx.0 | 30918 | 2021-07-10 13:57:35.837 | info | Connected  - local UDP Server listening on 192.168.10.11:50790
knx.0 | 30918 | 2021-07-10 13:57:33.836 | info | STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0).
knx.0 | 30918 | 2021-07-10 13:57:31.833 | info | Connected  - local UDP Server listening on 192.168.10.11:57448
knx.0 | 30918 | 2021-07-10 13:57:29.831 | info | STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0).
knx.0 | 30918 | 2021-07-10 13:57:27.829 | info | Connected  - local UDP Server listening on 192.168.10.11:51316
knx.0 | 30918 | 2021-07-10 13:57:25.828 | info | STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0).
knx.0 | 30918 | 2021-07-10 13:57:23.825 | info | Connected  - local UDP Server listening on 192.168.10.11:57186
knx.0 | 30918 | 2021-07-10 13:57:21.822 | info | STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0).
knx.0 | 30918 | 2021-07-10 13:57:19.820 | info | Connected  - local UDP Server listening on 192.168.10.11:41257
knx.0 | 30918 | 2021-07-10 13:57:17.817 | info | STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0).
knx.0 | 30918 | 2021-07-10 13:57:15.813 | info | Connected  - local UDP Server listening on 192.168.10.11:34172
knx.0 | 30918 | 2021-07-10 13:57:13.815 | info | STATE_NOT_CONNECTED : Stop connection :  STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 30918 | 2021-07-10 13:57:13.812 | info | STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0).

</body>
</html>`

**Comment by boellner** [comment] 2021-07-10 20:29
Duplicate of #184

**Comment by chefkoch009** [comment] 2021-11-20 18:07
Das bedeutet, das dein GW die Verbindung ablehnt. Vielleicht hast du zu viele Verbindungen zu diesem Gateway. Er schafft es nicht, mit dem Gateway zu kommunizieren. Das kann auch ein Netzwerkproblem sein.

**Comment by chefkoch009** [comment] 2021-12-03 08:42
Besteht das Problem mit der Adapter Version V2.x immer noch?

**Comment by chefkoch009** [comment] 2021-12-13 14:10
Anscheinend ist das behoben.

**Closed by chefkoch009** 2021-12-13 14:10 UTC
